version: '2'
services:
  web:
    build: .
    ports:
      - "1234:1234"
    links:
      - mongo
    environment:
      PORT: 1234
    command: /command.sh
    volumes:
      - ./src/:/usr/src/app/src/
      - ./node_modules:/usr/src/app/node_modules
      - ./command.sh:/command.sh

  db:
    image: mongo:3.5
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
